- id: doi:10.46586/tches.v2023.i4.32-57
  type: paper
  date: 2020-08-0
  image: images/basalisc-diagram.png
  buttons:
    - type: pdf
      text: PDF (eprint)
      link: https://eprint.iacr.org/2022/657.pdf 

- id: doi:10.5220/0006187703620371
  image: https://upload.wikimedia.org/wikipedia/commons/e/e7/KnnClassification.svg
